version: '3.3'

services:
  db:
    build: ./container/db/
    restart: always
    environment:
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: 'dev'
      MYSQL_ROOT_PASSWORD: 'devroot'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

  grafana:
    links:
      - db:db
    image: grafana/grafana-oss
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_DATABASE_HOST=CONTROLE_TRAFFIC:3306
      - GF_DATABASE_NAME=CONTROLE_TRAFFIC
      - GF_DATABASE_USER=dev
      - GF_DATABASE_PASSWORD=dev
      - GF_DATABASE_TYPE=mysql
      - GF_DATABASE_MAX_OPEN_CONN=300
    ports:
      - "3000:3000"
    depends_on: ["db"]

volumes:
  my-db:
  grafana-data:
