version: "3.9"

x-common-variables: &common-variables
  # DATABASE 
  MYSQL_HOST: "10.11.11.203" # A changer en fonction de la machine qui execute
  MYSQL_ROOT_PASSWORD: devroot
  MYSQL_DATABASE: CONTROLE_TRAFFIC
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev

  # MOSQUITTO
  MOSQUITTO_HOST: test.mosquitto.org
  MOSQUITTO_PORT: 1883
  MOSQUITTO_TOPIC_PERIODIQUE: "/data/periodique"  # "/ESP0008F21F/freemem",
  MOSQUITTO_TOPIC_PONCTUELLE: "/data/ponctuelle"  # "/ESP0008F21F/pmc"
  MOSQUITTO_USER: admin
  MOSQUITTO_PASSWORD: admin

services:
  grafana_db:
    image: mysql
    environment: *common-variables
    volumes:
      - ./container/db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  grafana:
    image: grafana/grafana-oss
    restart: on-failure
    environment: 
      GF_DATABASE_HOST: grafana_db:3306
      GF_DATABASE_NAME: CONTROLE_TRAFFIC
      GF_DATABASE_USER: dev
      GF_DATABASE_PASSWORD: dev
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_MAX_OPEN_CONN: 300
    ports:
      - "3000:3000"
    depends_on: 
      - grafana_db
    
  cdc:
    build: ./container/cdc/
    restart: on-failure
    environment: *common-variables
