version: "3.9"

x-common-variables: &common-variables
  # DATABASE 
  MYSQL_HOST: grafana_db
  MYSQL_ROOT_PASSWORD: devroot
  MYSQL_DATABASE: CONTROLE_TRAFFIC
  MYSQL_USER: dev
  MYSQL_PASSWORD: dev

  # MOSQUITTO
  MOSQUITTO_HOST: mosquitto
  MOSQUITTO_PORT: 1883
  MOSQUITTO_TOPIC_PERIODIQUE: "/data/periodique"
  MOSQUITTO_TOPIC_PONCTUELLE: "/data/ponctuelle"
  MOSQUITTO_USER: admin
  MOSQUITTO_PASSWORD: password

services:
  grafana_db:
    image: mysql
    environment: *common-variables
    volumes:
      - ./container/db:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 55

  grafana:
    image: grafana/grafana-oss
    restart: on-failure
    environment: 
      GF_DATABASE_HOST: grafana_db:3306
      GF_DATABASE_NAME: CONTROLE_TRAFFIC
      GF_DATABASE_USER: dev
      GF_DATABASE_PASSWORD: dev
      GF_DATABASE_TYPE: mysql
      GF_DATABASE_MAX_OPEN_CONN: 300
    ports:
      - "3000:3000"
    depends_on: 
      grafana_db:
        condition: service_healthy
    volumes:
      - ./config/grafana/provisioning:/etc/grafana/provisioning
  
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./config/mosquitto/:/mosquitto/config/:ro
      - ./log_mosquitto/:/mosquitto/log/
      - data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001
    
  cdc:
    build: ./container/cdc/
    restart: on-failure
    environment: *common-variables
    depends_on: 
      grafana_db:
        condition: service_healthy
      mosquitto:
        condition: service_started

  borne:
    build: ./container/borne/
    restart: on-failure
    environment: *common-variables
    depends_on:
      mosquitto:
        condition: service_started
      cdc:
        condition: service_started

volumes:
  data: ~
