apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: ${GF_DATABASE_HOST}
    database: ${GF_DATABASE_NAME}
    user: ${GF_DATABASE_USER}
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: ${GF_DATABASE_PASSWORD}
